### ISSUE TITLE
A little bit of everything

### ISSUE THREAD

**Issue by 3thre** [atareao/Touchpad-Indicator#10]
It doesn't start automatically as I set it
It doesn't 'turn off' when I start typing
The mouse point randomly just plants itself wherever it wants creating havoc with any post or writing I am attempting to do making everything take 3x longer to complete and my stress level to rise 
I've lost entire posts/emails/pieces of writing to this; I'm a pretty low key person but this issue has helped me get in touch with my inner nutcase

**Comment by atareao** [comment]
Some question in order to solve the bug,
1.- What distribution and version do you have installed?
2.- What desktop environment and version do you have installed?
3.- What Touchpad Indicator version do you have installed?
Thanks.

**Comment by 3thre** [comment]
2.0.3-0extras18.04.4
Linux Mint Sylvia

Thank you for getting in touch so quick <3

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by atareao** [comment]
And DE? Cinnamon, MATE,....?
Thanks

**Comment by 3thre** [comment]
No Cinnamon and I do not know what DE or MATE are

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by atareao** [comment]
I uploaded a new version. Touchpad Indicator is working for you now?
Thanks.

**Comment by hanswurst31** [comment]
hi where do i download the new version?

with

 sudo add-apt-repository ppa:atareao/atareao
sudo apt update
sudo apt install touchpad-indicator

its still the old one.


thx

**Comment by atareao** [comment]
@hanswurst31 so... Touchpad Indicator is working for you?

**Comment by 3thre** [comment]
Wrong person I think!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by atareao** [comment]
@3thre So, you are using Cinnamon in Linux Mint.
I uploaded a new version 2.0.4-0extras18.04.3. Do you try it?
Thanks

**Comment by 3thre** [comment]
Better than it had been. Much less of it randomly deciding to start typing at some other point in the paragraph etc but still, I'd say about 20%, it still does that but that is still a solid 35% reduction. Is there some setting that I could adjust that would make things less sensitive and/or responsive?
