### ISSUE TITLE
Disable touchpad on type -- ignore shift, ctl, alt, chords, function keys, escape, &c?

### ISSUE THREAD

**Issue by alsegno** [atareao/Touchpad-Indicator#11]
Is it possible to change the 'disable touchpad on type' behaviour so that it does not disable the touchpad when I have pressed 'control keys' like 'shift', 'alt', 'control', 'escape', or chords with these keys 'ctrl-c', 'ctrl-v', etc?

**Comment by atareao** [comment]
Hi @alsegno,
I think is a good idea.
I implemented this solution and it's working for me in a test version of Touchpad Indicator. 
But I don't know if include it as option or if it must be the default behaviour. 
What do you think about this?
