### ISSUE TITLE
crashes on launch on ubuntu 18.04

### ISSUE THREAD

**Issue by icorne** [atareao/Touchpad-Indicator#12]
What can I do to help identify the problem?

**Comment by atareao** [comment]
Hi,
What desktop environment do you have? Unity, GNOME, MATE, XFCE....
What version of Touchpad Indicator do you have installed?
Please. Exit of Touchpad Indicator and run it from terminal. Paste here the output.

**Comment by icorne** [comment]
Hello:

I'm running standard ubuntu 18.04 in xorg mode. It's got gnome shell 3.28 a

https://paste.ubuntu.com/p/rzH9nsCMm9/

**Comment by atareao** [comment]
Please run xinput and paste here the output

**Comment by icorne** [comment]
http://paste.ubuntu.com/p/ZGNfh2vsvB/

**Comment by atareao** [comment]
Hi,
Run this,
xinput --list-props 11
Thank for your help.

**Comment by icorne** [comment]
http://paste.ubuntu.com/p/jNkSFtvGyt/

**Comment by atareao** [comment]
Thanks. I will release a new version of Touchpad Indicator...

**Comment by icorne** [comment]
Great, thanks!

**Comment by atareao** [comment]
Did you try last version? Is working for you?
Thanks

**Comment by icorne** [comment]
Yes!
Thank you. Couldn't the option i wanted to work though. Can I log bugs for that as well? Not sure if this is the place

**Comment by atareao** [comment]
Yes, please, open a new issue
