### ISSUE TITLE
disable touchpad on typing does reflect xinput property

### ISSUE THREAD

**Issue by icorne** [atareao/Touchpad-Indicator#14]
![screenshot from 2018-04-12 18-43-43](https://user-images.githubusercontent.com/3259342/38691561-7abee2ee-3e81-11e8-8fc1-22211291fe7d.png)

» xinput list-props 11                                               ~  
Device 'DLL07A8:01 044E:120B':
	Device Enabled (142):	1
	Coordinate Transformation Matrix (144):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Tapping Enabled (280):	1
	libinput Tapping Enabled Default (281):	0
	libinput Tapping Drag Enabled (282):	1
	libinput Tapping Drag Enabled Default (283):	1
	libinput Tapping Drag Lock Enabled (284):	0
	libinput Tapping Drag Lock Enabled Default (285):	0
	libinput Tapping Button Mapping Enabled (286):	1, 0
	libinput Tapping Button Mapping Default (287):	1, 0
	libinput Natural Scrolling Enabled (288):	1
	libinput Natural Scrolling Enabled Default (289):	0
	libinput Disable While Typing Enabled (290):	1
	libinput Disable While Typing Enabled Default (291):	1
	libinput Scroll Methods Available (292):	1, 1, 0
	libinput Scroll Method Enabled (293):	1, 0, 0
	libinput Scroll Method Enabled Default (294):	1, 0, 0
	libinput Accel Speed (295):	0.000000
	libinput Accel Speed Default (296):	0.000000
	libinput Left Handed Enabled (297):	0
	libinput Left Handed Enabled Default (298):	0
	libinput Send Events Modes Available (265):	1, 1
	libinput Send Events Mode Enabled (266):	0, 0
	libinput Send Events Mode Enabled Default (267):	0, 0
	Device Node (268):	"/dev/input/event17"
	Device Product ID (269):	1102, 4619
	libinput Drag Lock Buttons (299):	<no items>
	libinput Horizontal Scroll Enabled (300):	1

**Comment by atareao** [comment]
When you select "disable touchpad from menu", it disables the touchpad?
Thanks

**Comment by atareao** [comment]
Touchpad Indicator disables the touchpad via software. Touchpad Indicator doesn't use xinput becouse not all touchpad have this feature.
