### ISSUE TITLE
Disable touchpad when typing option not working

### ISSUE THREAD

**Issue by fcaplette** [atareao/Touchpad-Indicator#16]
Hi,

The "Disable touchpad when typing" is not working for me. I am on Ubuntu 16.04, laptop Dell Inspiron 2-in-1. I tried to uninstall and reinstall, but the same issue is happening still.

Thanks!

**Comment by atareao** [comment]
Can you enable and disable the touchpad with the app?

**Comment by CRaFT4ik** [comment]
> Can you enable and disable the touchpad with the app?
No, enable and disable doesn't work. I have same problem. My laptop - dell inspiron 7567.

**Comment by MartinX3** [comment]
Not working on Ubuntu 16.04 and Ubuntu 18.04.
And because of bug https://github.com/atareao/Touchpad-Indicator/issues/15 I can't change the options.

**Comment by atareao** [comment]
@CRaFT4ik I uploaded a new version I think fix this bug for you.
Thanks

**Comment by CRaFT4ik** [comment]
@atareao Thank you! But PPA contains still the old version. When should expect this update?

**Comment by atareao** [comment]
@CRaFT4ik I Will upload in 8 hours i think

**Comment by tassiovirginio** [comment]
Thanks for the fix, on my Dell machine with Ubuntu 16.04 it also was not working properly. After the update is working as it should. He had a long waiting time, both to lock and unlock. Now it's okay

**Comment by fcaplette** [comment]
I downloaded the latest version and it now works perfectly on my dell machine as well, Ubuntu 16.04. Thank you!

**Comment by atareao** [comment]
@CRaFT4ik did you test new version?

**Comment by CRaFT4ik** [comment]
@atareao Yes, but it's not working for me.
When I tap "disable touchpad", it doesn't turn off. Log:
> ==== start set_touch_enabled =====
> set_touch_enabled: False
> are_all_touchpad_enabled:  True
> ==?==
Also, touchpad doesn't turn off when mouse plug in.

**Comment by atareao** [comment]
This configuration in from Desktop not from app.

**Comment by atareao** [comment]
What is your desktop environment, MATE, GNOME, KDE? What version of desktop? What distribution do you have installed? What version?
Thanks
