### ISSUE TITLE
"Disable touchpad when typing" lags over 1 second before disabling touchpad

### ISSUE THREAD

**Issue by michael-ts** [atareao/Touchpad-Indicator#28]
I very frequently find that I am typing yet my cursor will jump to a different location on the screen due to accidental touch on the touchpad which is directly beneath the keyboard on my laptop.  I have enabled the feature where the touchpad is supposed to be disabled as soon as I start typing, so I would expect that the instant a key is pressed the touchpad would be disabled, but this is not happening.

Today I was trying to get to the bottom of how this could happen when I noticed that it actually takes over 1 seconds from when I type a key until the visual appearance of the touchpad-indicator icon at the bottom of my screen changes and touchpad input is disabled, allowing ample time to start typing and immediately accidentally touch the touchpad resulting in my text going to the wrong location.  In fact, if I just press and hold a single key here is what I see before the touchpad is disabled: "111111111111111111111111111".  That's 27 characters that get typed before I no longer have to worry about accidentally hitting the touchpad.  When I am typing in a "stop and go" fashion this means that nearly every time I start typing I can have this problem.

I decided to play around with the timeout ("milliseconds to wait after the last key press before enabling the touchpad") to see if decreasing it would have any effect on this lag, as the delay in disabling the touchpad seems very similar to the delay after the last key until the touchpad is re-enabled.  To my surprise, when I decreased the timeout delay to only 300ms I find that it STILL takes over a second after my last keystroke before the touchpad is enabled again.    Even when I decrease the timeout to 0ms it still totally ignores it and takes about a second before the touchpad is disabled and over a second to re-enable.  (Edit: Ok, after re-opening I guess 300ms is the shortest delayed allowed.  The fact that I have to click "Ok" and realize that the software is taking a few seconds to restart itself instead of being able to just "Apply" without closing isn't helping, as because I just clicked Ok and assumed it would take and the box just closed there was no chance for it to correct me.  Too bad, I was going to try -800 next...)  In fact, it seems to take slightly longer to re-enable than the delay in disabling it.

**Comment by atareao** [comment]
Please, tell me:
What distribution and version do you have installed?
What version of touchpad indicator doyou have installed?

Thanks

**Comment by michael-ts** [comment]
"About" tells me the version of touchpad indicator is: 2.1.2-0extras 18.04.0
I'm running LUbuntu, although lsb_release -a  says I'm running "Ubuntu 18.04.1 LTS"

**Comment by michael-ts** [comment]
I went through and looked at the code. I see that a KeyboardMonitor object is created using the specified interval. I also see that keyboard_monitor is emitting key_pressed and key_released.  However it’s unclear to me exactly what this accomplishes, and I don't see where we actually use this to lock out the touchpad.
I removed the minimum value restriction and even going to a negative value (e.g. -300) there is still a bit of lag between when I start typing and when the touchpad gets locked out. However it seems like it stops locking out the keyboard from time to time even if I am typing fairly fast, so this does not seem like a good workaround.

**Comment by SwimminglyWell** [comment]
I just installed the latest version today from the ppa you recommended, and I have this problem as well. If it helps, I'm running lubuntu 18.04 on an HP Stream 14. I think there's also a problem in the lag, as I have the time set to disable for to 300 ms, but not only is the start delayed but the lag before I can use the touchpad again is delayed as well.

**Comment by michael-ts** [comment]
As a workaround I've had to disable the button taps.   It doesn't hurt anything (at least for me) for the pointer to be moving around while I'm trying to type if it doesn't get clicked.  At the same time, it seems like it would be useful as an option to only lock out tapping, because I frequently found myself typing and them immediately wanting to scroll using the touchpad only to find I had to wait another 800ms before I could do so.

**Comment by aynair** [comment]
> it would be useful as an option to only lock out tapping ...

Yes, that is a very good advice. I have the same problem with uncomfortable long lags when touchpad pointer is disabled while needed.
And it is easy to implement (-t option for syndeamon) ...

**Comment by iamonkara** [comment]
I have the exact same issue. 800ms wait time before touchpad is enabled and even with 800ms the lag between disabling touchpad creates a small window where the cursor jumps around while typing.

**Comment by iamonkara** [comment]
> I think what is happening is that the program is writing to the terminal, and then disabling the touchpad, and then writing to terminal, and then enabling it. They should really just remove these to make it function much faster. Note: run in terminal with "touchpad-indicator" to see this happening when you type

You are right!! I did see the output in the terminal with `touchpad-indicator` 

But its a difficult problem to solve. One potential solution will be to look for a swipe gesture instead of a tap gesture to enable the disabled touchpad.

**Comment by amine1996** [comment]
The best way I've found to reduce the lags is to modify the touchpad.py class.

I added a touchpad_ids class variable that is initialized with values from _get_ids().

In the functions disable_all_touchpads and enable_all_touchpads I removed the call to _get_ids() and replaced it with values from self.touchpad_ids.

This way the process is less heavy and it is much faster. Modifications done :

Touchpad constructor :

```

class Touchpad(object):
    def __init__(self):
        self.touchpad_ids = self._get_ids()
        pass

```

Functions :

```
    def disable_all_touchpads(self):
        for id in self.touchpad_ids:
            self.set_touchpad_disabled(id)
            time.sleep(MINIMUM_TIME)
        return True

    def enable_all_touchpads(self):
        for id in self.touchpad_ids:
            self.set_touchpad_enabled(id)
            time.sleep(MINIMUM_TIME)
        return True
```

**Comment by dbenesj** [comment]
> I don't understand why it was done this way, can the IDs change after the computer boot ?

It will not work for newly plugged touchpads. It would definitelly could be done in more optimal way, but I understand why it is done this way.

But thank you very much :+1:, it highly improves the lag and user experience!
And since I'm not connecting another touchpad I will use this changes...

**Comment by atareao** [comment]
Hi every one,
I upload a new version that fix this issue... I hope
Thanks for your support

**Comment by HankB** [comment]
Was this code incorporated into the code downloaded form the PPA? I found about 2 1/2 second delay in response to key press. I also find that typing on the keyboard can bee delayed by about the same amount of time. 
This is on a Toshiba Chromebook 2 with weak processor and Elan touchpad and running GalliumOS 3.0 (respin of Xubuntu 16.04.)

Thanks!

**Comment by thosecars82** [comment]
I just installed Touchpad Indicator 2.2.1-0extras19.04.0 in Ubuntu 18.04 with Kernel 5.4.0-050400-generic and LXDE as desktop environment
with the following commands
`sudo add-apt-repository ppa:atareao/atareao
sudo apt update
sudo apt install touchpad-indicator`

But the lag problem is still there. The lag is supposed to be 300 milliseconds but it is much more than that, may be around 2 seconds. Moreover, if I touch the touch-pad immediately after finishing typing, that means before the 2 seconds period is finished, then the touch-pad will not work until I stop touching it, regardless of the time I could have spend touching the touch-pad after finishing typing.

Can anyone provide any help with this?

Thanks

**Comment by ZitongZhouEric** [comment]
I can confirm this problem persists. Set delay to 300ms, experiencing at least 1s delay after typing.

`
Linux 6.5.0-45-generic
Ubuntu 22.04.4 LTS
2.2.3-ubuntu20.04.0
`
