### ISSUE TITLE
touchpad-indicator incompatible with libinput?

### ISSUE THREAD

**Issue by simonhf** [atareao/Touchpad-Indicator#3]
I installed touchpad-indicator on a new Dell Precision 5520 running Ubuntu 16.04 and it worked fine. I mainly installed it for the ability to have a key combo to disable the touchpad. However, the touchpad was still annoying so I tried out libinput. With libinput then the touchpad is very much less annoying and I am much happier. HOWEVER, touchpad-indicator no longer starts and silently dies after a few seconds. There is also no message in the syslog. I tried  starting  it manually and it says:

   "Couldn't find synaptics properties. No synaptics driver loaded?"

So is it just incompatible with libinput?

Thanks,
Simon

[1] https://gist.github.com/waltervargas/93178b2ac341a1a11d254fe97a2e798c

**Comment by atareao** [comment]
Fixed
