### ISSUE TITLE
How do I unhide the tray icon?

### ISSUE THREAD

**Issue by PierreTurnbull** [atareao/Touchpad-Indicator#36]
I find no way to unhide it. Even when I uninstall it and reinstall it with the following commands, it is still hidden:

```
sudo apt-get remove --autoremove touchpad-indicator
sudo apt-get install touchpad-indicator
```

The following command, which is supposed to show the icon if it is hidden, doesn't work:

```
touchpad-indicator --show-icon
```

It shows me this message instead:

```
<gettext.GNUTranslations object at 0x7f1227bd4630>
Another instance of Touchpad-Indicator is working
```

The consequence is that I can't access the settings of touchpad-indicator, which is a big problem.

**Comment by alaconda** [comment]
I have some issue.  Did you ever figure this out?  Any help would be greatly appreciated.

**Comment by PierreTurnbull** [comment]
I have never found a solution, sorry.

**Comment by alaconda** [comment]
@PierreTurnbull Not sure if you are still using this... but I found the solution in _https://github.com/atareao/Touchpad-Indicator/issues/15#issuecomment-394185944_

To disable auto start
`rm ~/.config/autostart/touchpad-indicator-autostart.desktop`

To reset configuration (or you can just modify this file to unhide the icon)
`rm -rf ~/.config/touchpad-indicator`

**Comment by tbergeron** [comment]
What @alaconda has suggested doesn't work for me.

The fact that this is a KNOWN issue and has been for months is mindblowing. I'm having the same issues no matter what I do. This is unusable, I will have to find an alternative.

#15 has been closed, yet no fix has ever been pushed. @atareao why???

**Comment by ro0NL** [comment]
*\*subcribes\**

**Comment by trinkner** [comment]
This issue remains a problem as of today, at least with the version available through the PPA.  I would state the version number, but I can't see it because of this problem....

I've uninstalled and reinstalled.  No fix.
I've uninstalled and deleted every file I can find that might configure touchpad-indicator, but the problem persists. 

Surely there is a file hidden somewhere that can be deleted or edited to fix this problem?

**Comment by trinkner** [comment]
I found a workaround to unhide the icon and regain access to the app's GUI.

1. Create text file: ~/.config/touchpad-indicator/touchpad-indicator.conf

2. Paste the following text into the newly created file:

{"first-time": false, "version": "2.2.1-0extras19.04.0", "is_working": false, "autostart": false, "on_mouse_plugged": false, "on_start": 1, "on_end": 1, "disable_on_typing": true, "interval": 800.0, "start_hidden": false, "show_notifications": true, "theme": "light", "touchpad_enabled": true, "natural_scrolling": true, "speed": 0.0, "tapping": true, "two_finger_scrolling": true, "edge_scrolling": false, "cicular_scrolling": true, "right-top-corner": 0, "right-bottom-corner": 0, "left-top-corner": 0, "left-bottom-corner": 0, "one-finger-tap": 0, "two-finger-tap": 0, "three-finger-tap": 0, "faulty-devices": ["11/2/1/0", "11/2/6/0", "11/2/a/0", "11/2/5/7326"]}

3. Save the file.  Those entries at the bottom of the file indicating faulty devices may be unique to my system.  Perhaps all you need in the file is the reference to the "start_hidden" variable.  Note that the misspelled "cicular" is what the program outputs, not my spelling mistake. 

4. Log out and back in.

Worked for me on Ubuntu 20.04.

And, of course, don't click "Start Hidden" or "Hide Icon" again.  :-)

**Comment by nscha** [comment]
@trinkner if it happens for you again, you might want to try the proposed fix I submitted, it's adding 3 lines to the touchpadindicator.py file to call the "make_visible" function. Not sure if the project is on hold, haven't received any comments on the PR
