### ISSUE TITLE
NameError: name 'syslog' is not defined

### ISSUE THREAD

**Issue by yochananmarqos** [atareao/Touchpad-Indicator#44]
I am the maintainer of [`touchpad-indicator-git`](https://aur.archlinux.org/packages/touchpad-indicator-git/). Using my package, everything was working fine on my Manjaro GNOME installation. However, after your recent commit 
(https://github.com/atareao/Touchpad-Indicator/commit/3ed32d64d2fe091ccc382e43aecee213eef8a588), it appears it no longer can detect devices. I've also lost the option to enable / disable the touchpad as it's greyed out in the context menu.

Arch Linux does not use syslog, it uses [systemd's journal](https://wiki.archlinux.org/index.php/Systemd/Journal).

```
$ touchpad-indicator -l
<gettext.GNUTranslations object at 0x7fa53031bc88>
Another instance of Touchpad-Indicator is working
Traceback (most recent call last):
  File "/usr/bin/touchpad-indicator", line 36, in <module>
    main()
  File "/usr/share/touchpad-indicator/touchpadindicator.py", line 713, in main
    device_list.list()
  File "/usr/share/touchpad-indicator/device_list.py", line 122, in list
    context.log_priority = syslog.LOG_EMERG
NameError: name 'syslog' is not defined
```

```
$ touchpad-indicator 
<gettext.GNUTranslations object at 0x7fa53031bc88>
#####################################################
Distributor: ManjaroLinux
Description: Manjaro Linux
Release: 18.0.4
Codename: Illyria
Architecture: x86_64
#####################################################

Touchpad-Indicator version: 2.2.0-0extras19.04.1ubuntu1
303 1
303 1
[Device('/sys/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input14'), Device('/sys/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input14/event6'), Device('/sys/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input14/mouse0')]
==== start set_touch_enabled =====
set_touch_enabled: False
are_all_touchpad_enabled:  True
==?==
==?== 1
==?== 2
[Device('/sys/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input14'), Device('/sys/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input14/event6'), Device('/sys/devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-1/3-1:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/input/input14/mouse0')]
=== 1 ===
==== start set_touch_enabled =====
set_touch_enabled: False
are_all_touchpad_enabled:  False
```

**Comment by cgarciaq** [comment]
I experience the same problem with Ubuntu 19 on a Dell Xps 13 9365.

> touchpad-indicator -l
<gettext.GNUTranslations object at 0x7f99cb5fa710>
Another instance of Touchpad-Indicator is working
Traceback (most recent call last):
  File "/usr/bin/touchpad-indicator", line 36, in <module>
    main()
  File "/usr/share/touchpad-indicator/touchpadindicator.py", line 713, in main
    device_list.list()
  File "/usr/share/touchpad-indicator/device_list.py", line 122, in list
    context.log_priority = syslog.LOG_EMERG
NameError: name 'syslog' is not defined

> xinput list-props 12
Device 'Wacom HID 4830 Pen stylus':
	Device Enabled (154):	1
	Coordinate Transformation Matrix (156):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (282):	0
	Device Accel Constant Deceleration (283):	1.000000
	Device Accel Adaptive Deceleration (284):	1.000000
	Device Accel Velocity Scaling (285):	10.000000
	Device Node (279):	"/dev/input/event5"
	Wacom Tablet Area (292):	0, 0, 29376, 16524
	Wacom Rotation (293):	0
	Wacom Pressurecurve (294):	0, 0, 100, 100
	Wacom Serial IDs (295):	18480, 0, 2, 0, 0
	Wacom Serial ID binding (296):	0
	Wacom Pressure Threshold (297):	26
	Wacom Sample and Suppress (298):	2, 4
	Wacom Enable Touch (299):	0
	Wacom Hover Click (300):	1
	Wacom Enable Touch Gesture (301):	0
	Wacom Touch Gesture Parameters (302):	0, 0, 250
	Wacom Tool Type (303):	"STYLUS" (281)
	Wacom Button Actions (304):	"Wacom button action 0" (305), "Wacom button action 1" (306), "Wacom button action 2" (307), "None" (0), "None" (0), "None" (0), "None" (0), "Wacom button action 3" (308)
	Wacom button action 0 (305):	1572865
	Wacom button action 1 (306):	1572866
	Wacom button action 2 (307):	1572867
	Wacom button action 3 (308):	1572872
	Wacom Pressure Recalibration (309):	1
	Wacom Panscroll Threshold (310):	1300
	Device Product ID (280):	1386, 18480
	Wacom Debug Levels (311):	0, 0

**Comment by yochananmarqos** [comment]
I forgot to close this as it was fixed in a recent commit. @cgarciaq, build it from the latest commit and you should be fine. Otherwise open a new issue.
